[package]
name = "FinSc-Topology-Wiki"
version = "0.1.0"
ipkg = "FinSc-Topology-Wiki.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Multiset-Ternary]
type = "local"
path = "../FinSc-Multiset-Ternary"
ipkg = "FinSc-Multiset-Ternary.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"

[custom.all.FinSc-Topology]
type = "local"
path = "../FinSc-Topology"
ipkg = "FinSc-Topology.ipkg"

[custom.all.FinSc-Electromagnetism]
type = "local"
path = "../FinSc-Electromagnetism"
ipkg = "FinSc-Electromagnetism.ipkg"
