[package]
name = "Idris2-Topology-Wiki"
version = "0.1.0"
ipkg = "Idris2-Topology-Wiki.ipkg"

[custom.all.Idris2-Multiset-Core]
type = "local"
path = "../Idris2-Multiset-Core"
ipkg = "Idris2-Multiset-Core.ipkg"

[custom.all.Idris2-Multiset-Transform]
type = "local"
path = "../Idris2-Multiset-Transform"
ipkg = "Idris2-Multiset-Transform.ipkg"

[custom.all.Idris2-Multiset-Ternary]
type = "local"
path = "../Idris2-Multiset-Ternary"
ipkg = "Idris2-Multiset-Ternary.ipkg"

[custom.all.Idris2-Geometry]
type = "local"
path = "../Idris2-Geometry"
ipkg = "Idris2-Geometry.ipkg"

[custom.all.Idris2-Topology]
type = "local"
path = "../Idris2-Topology"
ipkg = "Idris2-Topology.ipkg"

[custom.all.Idris2-Electromagnetism]
type = "local"
path = "../Idris2-Electromagnetism"
ipkg = "Idris2-Electromagnetism.ipkg"
